/*
 * Copyright (c) 2017, NXP Semiconductor, Inc.
 * All rights reserved.
 *
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __WIFI_SHIELD_GT202_H__
#define __WIFI_SHIELD_GT202_H__

#include "fsl_port.h"
#include "wifi_common.h"
#include "pin_mux.h"

/* This file cannot be included directly in common code, it must pass through "wifi_shield.h" */
#ifndef WIFISHIELD_ENABLED
#   define WIFISHIELD_ENABLED
#else
#   error "Other WiFi shield is already enabled !"
#endif

/* Pinmux function, generated by pinmuxtool */
#define WIFISHIELD_PINMUX_INIT BOARD_InitGT202Shield

/* WLAN_IRQ signal */
#define WIFISHIELD_WLAN_IRQn (PORTB_IRQn)
#define WIFISHIELD_WLAN_ISR PORTB_IRQHandler
#define WIFISHIELD_WLAN_IRQ_DIRECTION (kGPIO_DigitalInput)
#define WIFISHIELD_WLAN_IRQ_PORT (PORTB)
#define WIFISHIELD_WLAN_IRQ_GPIO (GPIOB)
#define WIFISHIELD_WLAN_IRQ_PIN (1)

/* WLAN_PWRON (PWRDWN) signal */
#define WIFISHIELD_WLAN_PWRON_DIRECTION (kGPIO_DigitalOutput)
#define WIFISHIELD_WLAN_PWRON_PORT (PORTB)
#define WIFISHIELD_WLAN_PWRON_GPIO (GPIOB)
#define WIFISHIELD_WLAN_PWRON_PIN (2)

/* INTMUX settings */
#define WIFISHIELD_WLAN_IRQ_INTMUX_INSTANCE 0
#define WIFISHIELD_WLAN_IRQ_INTMUX (INTMUX0)
#define WIFISHIELD_WLAN_IRQ_INTMUX_CHNL (1)
#define WIFISHIELD_WLAN_IRQ_INTMUX_CLOCKSRC (kCLOCK_Intmux0)
/* SPI settings */
#define WIFISHIELD_SPI (LPSPI0)
#define WIFISHIELD_SPI_INIT_CS (kLPSPI_Pcs2)
#define WIFISHIELD_SPI_XFER_CS (kLPSPI_MasterPcs2)
#define WIFISHIELD_SPI_CLOCKSRC (kCLOCK_Lpspi0)
#define WIFISHIELD_SPI_BAUDRATE (10000000)
#define WIFISHIELD_SPI_THRESHOLD (8)
#define WIFISHIELD_SPI_CLOCK (kCLOCK_Lpspi0)

/* INTMUX settings */
#define WIFISHIELD_SPI_INTMUX (INTMUX0)
#define WIFISHIELD_SPI_INTMUX_CHNL (0)

/* DMAMUX settings, interconnect SPI with DMA */
#define WIFISHIELD_DMAMUX (DMAMUX0)
#define WIFISHIELD_DMAMUX_RX_REQ (kDmaRequestMux0LPSPI0Rx)
#define WIFISHIELD_DMAMUX_TX_REQ (kDmaRequestMux0LPSPI0Tx)

/* DMA settings */
#define WIFISHIELD_DMA (DMA0)
#define WIFISHIELD_DMA_RX_CHNL (0)
#define WIFISHIELD_DMA_IM_CHNL (1)
#define WIFISHIELD_DMA_TX_CHNL (2)

#endif
